### ISSUE TITLE
dropbear does not start for me on rpi2

### ISSUE THREAD

**Issue by mlt** [grazzolini/mkinitcpio-dropbear#6]
I'm trying to follow [remote unlocking guide from the wiki](https://wiki.archlinux.org/index.php/Dm-crypt/Specialties#Remote_unlocking_of_the_root_.28or_other.29_partition). I think I followed all the steps, I can unlock my root with the keyboard, but somehow dropbear doesn't start as I can't ssh to it. I can ping the host while it waits for the keyboard input from `sd-encrypt` though. Without that hook, there is no way to boot it up at all. I'm not getting any suspicious error messages while building initrd either

```
sudo mkinitcpio -g /boot/initrd.gz
==> Starting build: 4.1.13-1-ARCH
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [systemd]
  -> Running build hook: [block]
  -> Running build hook: [keyboard]
  -> Running build hook: [dropbear]
Key is a ssh-rsa key
Wrote key to '/etc/dropbear/dropbear_rsa_host_key'
Key is a ssh-dss key
Wrote key to '/etc/dropbear/dropbear_dss_host_key'
Key is a ecdsa-sha2-nistp256 key
Wrote key to '/etc/dropbear/dropbear_ecdsa_host_key'
dropbear_rsa_host_key : md5 <some fingerprint>
dropbear_dss_host_key : md5 <some fingerprint>
dropbear_ecdsa_host_key : md5 <some fingerprint>
  -> Running build hook: [encryptssh]
  -> Running build hook: [sd-encrypt]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initrd.gz
==> Image generation successful
```

What shall I try? Any help is appreciated. Thanks!

**Comment by grazzolini** [comment]
Hi,

   It seems to me that you're missing some hooks in your mkinitcpio.conf. The dropbear hook is never meant to go alone. It need the netconf and utils hooks, from mkinitcpio-netconf and mkinitcpio-utils. Also, I think you still have the old dropbear_initrd_encrypt package installed. Or, at least, some reminiscent of it. And, sd-encrypt is meant to be used on systemd enabled initrd's. From your output, it doesn't seem to be the case. The encryptssh hook is meant to replace the encrypt hook, it allows both for unlocking through the keyboard and remotely. Just out of curiosity, why are you building your initrd using -g?

**Comment by mlt** [comment]
I should have mentioned that. I did try adding _netconf_, it makes no difference, and since I could ping the host, I thought that kernel or something already got network up along with IP. _mkinitcpio-utils_ contains _encryptssh_, and I do include that hook.
I'm somewhat new to Arch, and I haven't ever installed _dropbear_initrd_encrypt_.
Can detached header be a problem? _sd-encrypt_ (?) picks up `/etc/crypttab.initramfs` that mentions detached header, but I can't seem to find anything for encryptssh. I feel like I should patch it... Or shall dropbear get up no matter what?

**Comment by grazzolini** [comment]
Strictly speaking, netconf, dropbear and encryptssh are independent of each other. You can get networking and dropbear running, but be unable to remote unlock, because there is no encryptssh, for example.

That being said, they  don't support a detached header, and you will need to hack into encryptssh for adding support to it. I don't use a detached header myself, but if you add support for it and send me a patch for it, it could be included. And, as for sd-encrypt, I don't think it works without systemd.

**Comment by mlt** [comment]
> ... dropbear and encryptssh are independent of each other

That is what I thought. So it should be up.... I feel like I need to get that rescue shell into initrd.

> .. if you add support for it ..

I just follow the wiki for now. It needs to be altered to customize header location. I'll see if I can do it. I guess it would have to go into utils/encryptssh.

> sd-encrypt, I don't think it works without systemd

I do use systemd hook.

> why are you building your initrd using -g

Failed to address this one. It says dry-run without it. I'm not sure if there is any difference on Arch Linux ARM and I don't have any other platforms with Arch.

**Comment by mlt** [comment]
It just occurred to me that sd-encrypt made me lazy and I even had no cryptdevice in cmdline :innocent: Did I miss some mailing list discussion as where everything is going to? It seems from your replies, that you would not use systemd in initrd. I personally would like to have everything in crypttab.initramfs and keep cmdline clean. I'll still try to mess with dropbear later...

**Comment by mlt** [comment]
I removed systemd hook, and everything got into place! Well, at least dropbear was up. I copied and modified encryptssh to parse path to header (that I include with `FILES=` in mkinitcpio.conf) and I had to replace `cut -d:` with `cut -d\;` as USB disk id contains colon (like in `cryptdevice=/dev/disk/by-id/usb-WDC_WD20_00JB-00FUA0_0-0:0;desktop;header=/home/mlt/desktop.lks`). I can't use UUID as it is not available for whole disk. I'm not positive it is suitable for general use, but I post it here in case someone finds it useful.

``` diff
--- encryptssh  2015-11-17 23:02:29.000000000 -0600
+++ encryptssh.mlt      2015-11-18 20:22:57.439871931 -0600
@@ -38,9 +38,9 @@

         if [ -n "${cryptdevice}" ]; then
             DEPRECATED_CRYPT=0
-            cryptdev="$(echo "${cryptdevice}" | cut -d: -f1)"
-            cryptname="$(echo "${cryptdevice}" | cut -d: -f2)"
-            cryptoptions="$(echo "${cryptdevice}" | cut -d: -f3)"
+            cryptdev="$(echo "${cryptdevice}" | cut -d\; -f1)"
+            cryptname="$(echo "${cryptdevice}" | cut -d\; -f2)"
+            cryptoptions="$(echo "${cryptdevice}" | cut -d\; -f3)"
         else
             DEPRECATED_CRYPT=1
             cryptdev="${root}"
@@ -54,12 +54,17 @@

         OLDIFS="${IFS}"
         IFS=","
+        local headerFlag=false
         for cryptopt in ${cryptoptions}; do
             case ${cryptopt} in
                 allow-discards)
                     echo "Enabling TRIM/discard support."
                     cryptargs="${cryptargs} --allow-discards"
                     ;;
+                header*)
+                    cryptargs="${cryptargs} --header $(echo "${cryptopt}" | cut -d= -f2)"
+                    headerFlag=true
+                    ;;
                 *)
                     echo "Encryption option '${cryptopt}' not known, ignoring." >&2
                     ;;
@@ -72,7 +77,7 @@
         echo ${cryptargs} > /.cryptargs

         if resolved=$(resolve_device "${cryptdev}" ${rootdelay}); then
-            if /sbin/cryptsetup isLuks ${resolved} >/dev/null 2>&1; then
+            if $headerFlag || /sbin/cryptsetup isLuks ${resolved} >/dev/null 2>&1; then
                 [ ${DEPRECATED_CRYPT} -eq 1 ] && warn_deprecated
                 dopassphrase=1
                 # If keyfile exists, try to use that
```

**Comment by grazzolini** [comment]
Nice to hear things working! I don't know what is your specific need for a detached header, but you are aware that the mere fact of changing the hook to look for it, already make you loose the "deniability". The only remaining benefit is the fact that you deny an attacker the possibility of copying your LUKS header, in an evil maid attack.

If you want to hide the fact that you're using a encrypted root partition, I'd suggest you go plain dm-crypt, with no LUKS.

**Comment by mlt** [comment]
How about removing an SD card from my raspberry pi along with bootloader and /boot and stashing it away? :sunglasses: I know it won't help in Guantanamo :fearful: But it looks pretty to me.

**Comment by grazzolini** [comment]
This hook was developed to allow you to remote unlock a root partition. This obviously trades some security, by convenience. You could have a encrypted boot partition with GRUB's cryptodisk functionality, you can use plain dm-crypt, you can do lots of things and try to deny you have an encrypted disk at all, beside the fact that your entire hard drive contains random gibberish (you did overwrite your entire HD, right?).

With your suggested setup, you loose the ability to remote unlock your root partition, unless your SD card is present. But it surely can be done.

**Comment by mlt** [comment]
Raspberry pi has no GRUB but loads a kernel more or less directly off FAT partition. Neither I have a keyboard connected. While I do have to insert the card (or keep it :innocent:), but at least I can leave the keyboard alone. So these hooks suit my needs well. Thanks! _Remote_ for me means standing next to it without keyboard connected :wink: And yes, I did wipe the disk by writing /dev/zero on top of encrypted device :sunglasses:

**Comment by grazzolini** [comment]
The advice is to wipe with random data, it takes a hell lot of time, but prevent a lot of cryptanalysis. I'll take a look into implementing your changes into the hooks in a way that don't compromise deniability. It'll be a nice challenge.

**Comment by mlt** [comment]
Thank you for engaging in such lasting discussion :+1: Well, the rumor is that using /dev/urandom (if you mean that) is not as good as writing /dev/zero (or anything else) on top of encrypted device (e.g. /dev/mapper/root) thus generating higher entropy stream on disk itself compared to urandom.
It would be nice to adopt crypttab.initramfs to hide away all crypto stuff from the command line. And, hopefully, the last question. So was it systemd hook that initialized network for me before when I had no `ip=` option and no _netconf_ hook? It just seems redundant to supply that for DHCP and it seems like mkinitcpio-netconf does require that option.
P.S. Also it would be nice to explicitly mention for users to make sure there is no _systemd_ in HOOKS line.

**Comment by grazzolini** [comment]
Well, I don't know where you heard that rumour, but anything that isn't random aids in cryptanalysis. Let's say your attacker gets access to your encrypted disks in two occasions. He will know how much you fs grew between the two occasions, by that proving that you have a encrypted partition there, not just random gibberish.

The safe option is to use /dev/random, but on a 1TB disk it might take you a week to overwrite the whole disk. /dev/urandom is better than /dev/zero, hands down. There are an option using AES-NI also. But zeroing isn't the best option.

As for your initramfs, you should have another hook dealing with network (perhaps net?) because if netconf isn't there, it won't configure anything. Specially if you don't have an ip= option in your cmdline. I don't make any mention explicitly to check for systemd hook, simply because it ain't the default.

**Comment by mlt** [comment]
> He will know how much you fs grew

They won't. Perhaps, I was not clear explaining myself, I followed [the wiki](https://wiki.archlinux.org/index.php/Dm-crypt/Drive_preparation#dm-crypt_wipe_on_an_empty_disk_or_partition). It is gibberish from /dev/zero because of going through encryption. I don't know if that is faster. But my gut feeling is that it is faster than /dev/random, and better than /dev/urandom .... and AES-NI is not an option on RPI2. There is support for NEON bit slice implementation for AES AFAIK. I think it is slightly different.

> you should have another hook dealing with network (perhaps net?)

I remember seeing _net_ being outdated so I didn't even try. I did have `ip=` (I think) but I had neither `net` nor `netconf` that you pointed out. I had an impression that a [kernel did it on its own](https://www.kernel.org/doc/Documentation/filesystems/nfs/nfsroot.txt).

> because it ain't the default

I don't recall details. Perhaps you are right, but apparently it was confusing enough for Arch noob like myself to start this thread :smile: . Just IMHO...

**Comment by grazzolini** [comment]
> They won't. Perhaps, I was not clear explaining myself, I followed the wiki. It is gibberish from /dev/zero because of going through encryption. I don't know if that is faster. But my gut feeling is that it is faster than /dev/random, and better than /dev/urandom .... and AES-NI is not an option on RPI2. There is support for NEON bit slice implementation for AES AFAIK. I think it is slightly different.

/dev/zero, pretty much as the name implies, stream zeroes from it. Of course it is way, way faster than urandom or random. Your disk will have only zeroes in it. That wiki article used to have more advices, I don't know what changed, but, LUKS is just adding a header to the disk and nothing else. It won't overwrite it in any way. Take for example TrueCrypt or Veracrypt. It will overwrite the entire file/partition to specifically avoid this kind of cryptanalysis. I strongly suggest you use at least urandom to prepare your disks for LUKS. As slow as it might be.

> I remember seeing net being outdated so I didn't even try. I did have ip= (I think) but I had neither net nor netconf that you pointed out. I had an impression that a kernel did it on its own.

No, the kernel need ipconfig. So, you'd probably got another machine answering or you were with the net hook working.

> I don't recall details. Perhaps you are right, but apparently it was confusing enough for Arch noob like myself to start this thread :smile: . Just IMHO...

Don't worry. These concepts apply to pretty much every linux, since I believe almost all of them use initrd. Before I would write these hooks for Arch, I had a very similar setup on Ubuntu. It's nice to see these hooks being used in an unintended form, such as rpi's, arduinos and the like. I personally use them for remote unlocking physical and cloud servers with LUKS.
